server:
  port: ${HTTP_SERVER_PORT:8081}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}
    security:
      enabled: false

logging:
  level:
    root: ${LOG_ROOT:INFO}
    org.springframework: ${LOG_SPRING:INFO}
    org.springframework.jdbc: ${LOG_SPRING_JDBC:INFO}
    org.springframework.security: ${LOG_SPRING_SECURITY:INFO}
    com.github.erodriguezg.grpcjavalab.server: ${LOG_APP:INFO}