server:
  port: ${HTTP_SERVER_PORT:8081}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}

spring:
  application:
    name: grpc-java-server
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  flyway:
    enabled: true
    baseline-on-migrate: true
  jdbc:
    template:
      query-timeout: 30
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: ${LOG_ROOT:INFO}
    org.springframework: ${LOG_SPRING:INFO}
    org.springframework.jdbc: ${LOG_SPRING_JDBC:INFO}
    org.springframework.security: ${LOG_SPRING_SECURITY:INFO}
    com.github.erodriguezg.grpcjavalab.server: ${LOG_APP:INFO}