server:
  port: ${HTTP_SERVER_PORT:8082}

security:
  basic:
    enabled: false

spring:
  application:
    name: grpc-java-web
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  threads:
    virtual:
      enabled: true
  thymeleaf:
    enabled: true
    cache: ${THYMELEAF_CACHE:true}

grpc:
  client:
    usuario-service:
      address: ${GRPC_USUARIO_SERVICE_ENDPOINT:static://localhost:9091}
      negotiationType: ${GRPC_USUARIO_SERVICE_NEGOTIATION_TYPE:plaintext}

logging:
  level:
    root: ${LOG_ROOT:INFO}
    org.springframework: ${LOG_SPRING:INFO}
    org.springframework.security: ${LOG_SPRING_SECURITY:INFO}
    com.github.erodriguezg.grpcjavalab.web: ${LOG_APP:INFO}